import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, relative, dirname } from 'path';
import ora from 'ora';
import chalk from 'chalk';
import { callAI } from '../ai/index.js';
import { homedir } from 'os';

export async function generateWiki(cwd, scanResult, onProgress) {
  const globalConfigPath = join(homedir(), '.octboos', 'config.json');

  if (!existsSync(globalConfigPath)) {
    return { skipped: true, count: 0 };
  }

  const globalConfig = JSON.parse(readFileSync(globalConfigPath, 'utf8'));
  if (!globalConfig.apiKey) {
    return { skipped: true, count: 0 };
  }

  const files = scanResult.files || [];
  const modules = groupFilesIntoModules(files, cwd);
  const wikiDir = join(cwd, '.agent', 'wiki');;

  if (!existsSync(wikiDir)) {
    mkdirSync(wikiDir, { recursive: true });
  }

  const provider = globalConfig.provider || 'claude';
  const apiKey = globalConfig.apiKey;
  const generatedModules = [];

  for (const [moduleName, moduleFiles] of Object.entries(modules)) {
    const spinner = ora({ text: chalk.gray(`${moduleName} module...`), color: 'cyan' }).start();

    try {
      const content = await generateModuleWiki(moduleName, moduleFiles, cwd, provider, apiKey);
      writeFileSync(join(wikiDir, `${moduleName}.md`), content);
      generatedModules.push(moduleName);
      spinner.succeed(chalk.green(`${moduleName} module → .agent/wiki/${moduleName}.md`));
    } catch (err) {
      spinner.fail(chalk.red(`${moduleName} module — ${err.message}`));
      onProgress?.(moduleName, false, err.message);
    }
  }

  updateWikiIndex(wikiDir, generatedModules);
  return { skipped: false, count: generatedModules.length, modules: generatedModules };
}

function groupFilesIntoModules(files, cwd) {
  const modules = {};
  const maxFiles = 10;

  for (const file of files) {
    const rel = relative(cwd, file);
    const parts = rel.split('/');
    let moduleName;

    if (parts.length === 1 || !parts[0]) {
      moduleName = 'project';
    } else if (parts[0] === 'src' && parts[1]) {
      moduleName = parts[1];
    } else {
      moduleName = parts[0];
    }

    if (!modules[moduleName]) modules[moduleName] = [];
    if (modules[moduleName].length < maxFiles) {
      modules[moduleName].push(rel);
    }
  }

  return modules;
}

async function generateModuleWiki(moduleName, filePaths, cwd, provider, apiKey) {
  const fileContents = filePaths.map(path => {
    try {
      const fullPath = join(cwd, path);
      const allLines = readFileSync(fullPath, 'utf8').split('\n');
      const first100 = allLines.slice(0, 100).join('\n');
      return `--- ${path} ---\n${first100}`;
    } catch {
      return `--- ${path} ---\n[Unable to read file]`;
    }
  }).join('\n\n');

  const userMessage = `Module: ${moduleName}
Files: ${filePaths.join(', ')}

${fileContents}

Generate a wiki page with:
# ${moduleName}
## Purpose
## Key Files
## How it works
## Important functions/exports`;

  const content = await callAI(provider, apiKey, [
    { role: 'system', content: 'You are a code documentation expert. Analyze the provided code files and generate a concise wiki page in markdown format. Be brief and practical. Max 300 words.' },
    { role: 'user', content: userMessage },
  ]);

  return content.trim();
}

function updateWikiIndex(wikiDir, modules) {
  const lines = [
    `# Wiki Index`,
    ``,
    `## Modules`,
    ``,
  ];

  for (const module of modules.sort()) {
    lines.push(`- [${module}](${module}.md)`);
  }

  lines.push(
    ``,
    `---`,
    ``,
    `*Generated by Octboos on ${new Date().toISOString().split('T')[0]}*`,
  );

  writeFileSync(join(wikiDir, 'INDEX.md'), lines.join('\n'));
}
