import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

// All supported AI tool adapters
export const ADAPTERS = {
  claude: {
    name:        'Claude Code',
    file:        'CLAUDE.md',
    description: 'Anthropic Claude Code',
  },
  codex: {
    name:        'Codex / OpenCode',
    file:        'AGENTS.md',
    description: 'OpenAI Codex CLI & OpenCode',
  },
  cursor: {
    name:        'Cursor',
    file:        '.cursor/rules',
    description: 'Cursor IDE',
  },
  windsurf: {
    name:        'Windsurf',
    file:        '.windsurfrules',
    description: 'Windsurf IDE',
  },
  copilot: {
    name:        'GitHub Copilot',
    file:        '.github/copilot-instructions.md',
    description: 'GitHub Copilot',
  },
  gemini: {
    name:        'Gemini CLI',
    file:        'GEMINI.md',
    description: 'Google Gemini CLI',
  },
  antigravity: {
    name:        'Antigravity',
    file:        '.antigravity/rules.md',
    description: 'Antigravity IDE',
  },
  aider: {
    name:        'Aider',
    file:        '.aider.conf.yml',
    description: 'Aider AI Pair Programming',
  },
  cline: {
    name:        'Cline',
    file:        '.clinerules',
    description: 'Cline AI Coding Assistant',
  },
  continue: {
    name:        'Continue.dev',
    file:        '.continue/config.json',
    description: 'Continue.dev AI Coding Assistant',
  },
};

export function getStack(scanResult) {
  const all = [];
  if (scanResult && scanResult.frameworks && scanResult.frameworks.length > 0) {
    all.push(...scanResult.frameworks);
  }
  if (scanResult && scanResult.stack && scanResult.stack.length > 0) {
    all.push(...scanResult.stack);
  }
  const unique = [...new Set(all)].filter(Boolean);
  if (unique.length === 0) {
    return 'Vanilla JavaScript/TypeScript (no framework detected)';
  }
  return unique.join(', ');
}

export function getArchitecture(scanResult) {
  const dirs = (scanResult && scanResult.structure) || [];
  if (dirs.length === 0) {
    return 'Single-folder flat project structure.';
  }
  
  const purposeMap = {
    src: 'Main source code of the application',
    bin: 'Command-line interface binaries/scripts',
    test: 'Testing suite',
    tests: 'Testing suite',
    public: 'Static assets and public assets',
    components: 'Reusable UI components',
    app: 'Application core and routing (App Router)',
    pages: 'React page components (Pages Router)',
    lib: 'Shared helper functions and libraries',
    utils: 'Utility helper modules',
    config: 'Configuration and setup files',
    docs: 'Documentation and guides',
    db: 'Database schemas and migrations',
    prisma: 'Prisma database schemas',
    adapters: 'Third-party API adapters and integrations',
    indexer: 'Indexer and scanner logic',
    ui: 'User interface components and styling',
  };
  
  return dirs.slice(0, 10).map(dir => {
    const key = dir.toLowerCase();
    const desc = purposeMap[key] || 'Project module directory';
    return `- \`${dir}/\` — ${desc}`;
  }).join('\n');
}

export function getConventions(cwd) {
  if (!cwd) return '- Refer to .agent/style.md for coding conventions.';
  const stylePath = join(cwd, '.agent', 'style.md');
  if (!existsSync(stylePath)) {
    return '- Refer to .agent/style.md for coding conventions.';
  }
  
  try {
    const content = readFileSync(stylePath, 'utf8');
    if (content.includes('Edit this file to teach Octboos')) {
      return '- Refer to .agent/style.md for full coding style, architecture patterns, and conventions.';
    }
    
    // User custom conventions: extract bullets
    const lines = content.split('\n')
      .map(line => line.trim())
      .filter(line => line.startsWith('-') || line.startsWith('##') || line.startsWith('#'))
      .filter(line => !line.includes('Edit this file') && !line.includes('Last updated'))
      .slice(0, 15);
    
    return lines.join('\n') || '- Refer to .agent/style.md for coding conventions.';
  } catch {
    return '- Refer to .agent/style.md for coding conventions.';
  }
}

export function buildAgentsContent(projectName, scanResult, cwd) {
  const stack = getStack(scanResult);
  const arch = getArchitecture(scanResult);
  const conventions = getConventions(cwd);

  return `# ${projectName || 'Project'} — AI Context

> Generated by octboos

## Stack

${stack}

## Architecture

${arch}

## Conventions

${conventions}

## Before every task

1. Read .agent/protocol.md for execution protocol
2. Check .agent/map.md for file structure
3. Follow conventions above
4. After task: update .agent/wiki/[module].md
`;
}

export function buildClaudeContent(projectName, scanResult, cwd) {
  const base = buildAgentsContent(projectName, scanResult, cwd);
  
  let testCmd = 'npm test';
  let devCmd = 'npm run dev';
  if (scanResult && scanResult.packageJson) {
    const scripts = scanResult.packageJson.scripts || {};
    if (scripts.test) testCmd = 'npm test';
    else if (scripts.spec) testCmd = 'npm run spec';
    
    if (scripts.dev) devCmd = 'npm run dev';
    else if (scripts.start) devCmd = 'npm start';
  }

  return `${base}

## Claude-Specific Instructions

- Primary development command: \`${devCmd}\`
- Testing command: \`${testCmd}\`
- Prefer modular, clean, and self-documenting implementation.
- Refuse to write low-quality, complex, or repetitive code.
`;
}

export function generateAdapterContent(adapterKey, projectName, scanResult, cwd) {
  const masterContent = buildAgentsContent(projectName, scanResult, cwd);

  switch (adapterKey) {
    case 'claude':
      return buildClaudeContent(projectName, scanResult, cwd);

    case 'codex':
    case 'gemini':
    case 'antigravity':
    case 'cursor':
    case 'windsurf':
    case 'copilot':
    case 'cline':
      return masterContent;

    case 'aider':
      return `# Standard aider configuration that works with octboos
# Referenced from AGENTS.md
model: claude-3-5-sonnet-20241022
edit-format: draft
no-suggest: false
auto-commits: false
`;

    case 'continue':
      return `{
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20241022"
    }
  ],
  "autopilot": false,
  "contextProviders": [
    {
      "name": "octboos",
      "description": "Loads octboos context files",
      "priority": 10
    }
  ]
}`;

    default:
      return masterContent;
  }
}
