import { readFileSync, existsSync } from 'fs';
import { join, extname, relative } from 'path';
import fg from 'fast-glob';
import { execSync } from 'child_process';

// File extensions by language
const LANG_MAP = {
  '.ts': 'TypeScript', '.tsx': 'TypeScript/React',
  '.js': 'JavaScript', '.jsx': 'JavaScript/React',
  '.py': 'Python',     '.go': 'Go',
  '.rs': 'Rust',       '.java': 'Java',
  '.php': 'PHP',       '.rb': 'Ruby',
  '.vue': 'Vue',       '.svelte': 'Svelte',
  '.css': 'CSS',       '.scss': 'SCSS',
  '.sql': 'SQL',       '.prisma': 'Prisma',
};

// Framework detection by file presence
const FRAMEWORK_SIGNALS = [
  { file: 'next.config.js',        name: 'Next.js' },
  { file: 'next.config.ts',        name: 'Next.js' },
  { file: 'nuxt.config.ts',        name: 'Nuxt.js' },
  { file: 'nuxt.config.js',        name: 'Nuxt.js' },
  { file: 'vite.config.ts',        name: 'Vite' },
  { file: 'vite.config.js',        name: 'Vite' },
  { file: 'remix.config.js',       name: 'Remix' },
  { file: 'astro.config.mjs',      name: 'Astro' },
  { file: 'astro.config.ts',       name: 'Astro' },
  { file: 'astro.config.js',       name: 'Astro' },
  { file: 'svelte.config.js',      name: 'SvelteKit' },
  { file: 'angular.json',          name: 'Angular' },
  { file: 'manage.py',             name: 'Django' },
  { file: 'requirements.txt',      name: 'Python' },
  { file: 'Cargo.toml',            name: 'Rust' },
  { file: 'go.mod',                name: 'Go' },
  { file: 'composer.json',         name: 'PHP/Laravel' },
  { file: 'artisan',               name: 'Laravel' },
];

const IGNORE_DIRS = [
  '**/node_modules/**', '**/.git/**', '**/dist/**',
  '**/build/**', '**/.next/**', '**/coverage/**',
  '**/.agent/**', '**/vendor/**', '**/__pycache__/**'
];

export async function scanProject(cwd = process.cwd()) {
  const result = {
    stack:      [],
    frameworks: [],
    languages:  {},
    structure:  [],
    fileCount:  0,
    hasTests:   false,
    hasPrisma:  false,
    hasDocker:  false,
    packageJson: null,
    gitIgnore:  null,
  };

  // Read package.json if exists
  const pkgPath = join(cwd, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      result.packageJson = JSON.parse(readFileSync(pkgPath, 'utf8'));
      result.stack.push(...detectFromPackageJson(result.packageJson));
    } catch {}
  }

  // Detect frameworks by file presence
  for (const signal of FRAMEWORK_SIGNALS) {
    if (existsSync(join(cwd, signal.file))) {
      result.frameworks.push(signal.name);
    }
  }

  // Scan all files
  const files = await fg('**/*', {
    cwd,
    ignore: IGNORE_DIRS,
    onlyFiles: true,
    dot: false,
  });

  result.fileCount = files.length;

  // Count languages
  for (const file of files) {
    const ext = extname(file);
    if (LANG_MAP[ext]) {
      result.languages[LANG_MAP[ext]] = (result.languages[LANG_MAP[ext]] || 0) + 1;
    }
    if (file.includes('.test.') || file.includes('.spec.') || file.includes('__tests__')) {
      result.hasTests = true;
    }
    if (file.endsWith('.prisma')) result.hasPrisma = true;
    if (file === 'Dockerfile' || file === 'docker-compose.yml') result.hasDocker = true;
  }

  // Build top-level structure
  const topLevel = await fg('*', {
    cwd,
    ignore: IGNORE_DIRS,
    onlyDirectories: true,
  });
  result.structure = topLevel;

  return result;
}

function detectFromPackageJson(pkg) {
  const stack = [];
  const allDeps = {
    ...pkg.dependencies || {},
    ...pkg.devDependencies || {}
  };

  const checks = [
    ['next',           'Next.js'],
    ['react',          'React'],
    ['vue',            'Vue'],
    ['svelte',         'Svelte'],
    ['nuxt',           'Nuxt.js'],
    ['astro',          'Astro'],
    ['@remix-run/react', 'Remix'],
    ['@angular/core',  'Angular'],
    ['@sveltejs/kit',  'SvelteKit'],
    ['express',        'Express'],
    ['fastify',        'Fastify'],
    ['prisma',         'Prisma'],
    ['@prisma/client', 'Prisma'],
    ['mongoose',       'MongoDB/Mongoose'],
    ['typeorm',        'TypeORM'],
    ['drizzle-orm',    'Drizzle ORM'],
    ['tailwindcss',    'Tailwind CSS'],
    ['@mui/material',  'Material UI'],
    ['next-auth',      'NextAuth'],
    ['@clerk/nextjs',  'Clerk Auth'],
    ['zod',            'Zod'],
    ['trpc',           'tRPC'],
    ['graphql',        'GraphQL'],
    ['socket.io',      'Socket.io'],
    ['typescript',     'TypeScript'],
    ['vite',           'Vite'],
    ['webpack',        'Webpack'],
    ['jest',           'Jest'],
    ['vitest',         'Vitest'],
    ['playwright',     'Playwright'],
  ];

  for (const [dep, name] of checks) {
    if (allDeps[dep]) stack.push(name);
  }

  return stack;
}

export function buildFileMap(scanResult, cwd) {
  const lines = [];

  lines.push('# Project File Map');
  lines.push(`> Generated by Octboos`);
  lines.push('');

  // Combine Frameworks and Stack for compression
  const allStack = [...(scanResult.frameworks || []), ...(scanResult.stack || [])];
  const uniqueStack = [...new Set(allStack)].filter(Boolean);
  if (uniqueStack.length > 0) {
    lines.push(`## Stack: ${uniqueStack.slice(0, 8).join(', ')}`);
  }

  // Languages
  const langs = Object.entries(scanResult.languages || {})
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([l]) => l);
  if (langs.length > 0) {
    lines.push(`## Languages: ${langs.join(', ')}`);
  }

  lines.push('');

  // Directory structure
  if (scanResult.structure && scanResult.structure.length > 0) {
    lines.push('## Directory Structure');
    
    const purposeMap = {
      src: 'Main source code of the application',
      bin: 'Command-line interface binaries/scripts',
      test: 'Testing suite',
      tests: 'Testing suite',
      public: 'Static files and public assets',
      components: 'Shared UI components',
      app: 'Application core and routing (App Router)',
      pages: 'React views and routing (Pages Router)',
      lib: 'Helper utility functions',
      utils: 'Utility helper modules',
      config: 'Setup and configuration files',
      docs: 'Documentation files',
      db: 'Database schemas and migrations',
      prisma: 'Prisma database schemas',
      adapters: 'Third-party integrations',
      indexer: 'Project indexer and scanner components',
      ui: 'UI styling and layout components',
    };

    const dirs = scanResult.structure.slice(0, 15);
    for (const dir of dirs) {
      const key = dir.toLowerCase();
      const desc = purposeMap[key] || 'Project module directory';
      lines.push(`- \`${dir}/\` — ${desc}`);
    }
  }

  // Features
  const features = [];
  if (scanResult.hasTests)  features.push('Tests');
  if (scanResult.hasPrisma) features.push('Prisma ORM');
  if (scanResult.hasDocker) features.push('Docker');
  if (features.length > 0) {
    lines.push('');
    lines.push(`## Features: ${features.join(', ')}`);
  }

  lines.push('');
  lines.push(`## Stats`);
  lines.push(`- Total files: ${scanResult.fileCount}`);

  // Enforce max 50 lines strictly
  if (lines.length > 45) {
    return lines.slice(0, 43).concat(['...', `*Truncated to maintain strict 50-line limit (Total files: ${scanResult.fileCount})*`]).join('\n');
  }

  return lines.join('\n');
}

export function detectInstalledTools() {
  const result = {
    detected: [],
    uncertain: [],
    notFound: ['claude', 'opencode', 'cursor', 'aider', 'gemini', 'codex', 'windsurf']
  };

  // Tools to check via which/where
  const cliTools = [
    { name: 'claude', command: 'claude' },
    { name: 'opencode', command: 'opencode' },
    { name: 'cursor', command: 'cursor' },
    { name: 'aider', command: 'aider' },
    { name: 'gemini', command: 'gemini' },
    { name: 'codex', command: 'codex' },
    { name: 'windsurf', command: 'windsurf' }
  ];

  // Check CLI tools
  for (const tool of cliTools) {
    try {
      const platform = process.platform;
      let command;
      if (platform === 'win32') {
        command = `where ${tool.command}`;
      } else {
        command = `which ${tool.command}`;
      }
      execSync(command, { stdio: 'ignore' });
      // Move from notFound to detected
      result.detected.push(tool.name);
      result.notFound = result.notFound.filter(t => t !== tool.name);
    } catch (err) {
      // Tool not found via CLI, keep in notFound for now
    }
  }

  // Check common paths
  const home = process.env.HOME || process.env.USERPROFILE;
  const localAppData = process.env.LOCALAPPDATA;
  const appData = process.env.APPDATA;

  // Mac paths
  const macPaths = [
    { tool: 'cursor', path: '/Applications/Cursor.app' },
    { tool: 'windsurf', path: '/Applications/Windsurf.app' },
    { tool: 'claude', path: `${home}/.claude/` },
    { tool: 'aider', path: `${home}/.config/aider/` }
  ];

  // Windows paths
  const winPaths = [
    { tool: 'cursor', path: `${localAppData}\\Programs\\cursor` },
    { tool: 'claude', path: `${appData}\\Claude\\` }
  ];

  const pathsToCheck = process.platform === 'win32' ? winPaths : macPaths;

  for (const { tool, path } of pathsToCheck) {
    try {
      if (existsSync(path)) {
        // Move from notFound to detected if not already there
        if (!result.detected.includes(tool)) {
          result.detected.push(tool);
          result.notFound = result.notFound.filter(t => t !== tool);
        }
        // If we found it via path but not CLI, mark as uncertain
        if (!result.detected.includes(tool)) {
          result.uncertain.push(tool);
          result.notFound = result.notFound.filter(t => t !== tool);
          result.detected = result.detected.filter(t => t !== tool);
        }
      }
    } catch (err) {
      // Path doesn't exist or other error
    }
  }

  // Remove duplicates
  result.detected = [...new Set(result.detected)];
  result.uncertain = [...new Set(result.uncertain)];
  result.notFound = [...new Set(result.notFound)];

  return result;
}
