import { readFileSync, existsSync } from 'fs';
import { join, extname, relative } from 'path';
import fg from 'fast-glob';

// File extensions by language
const LANG_MAP = {
  '.ts': 'TypeScript', '.tsx': 'TypeScript/React',
  '.js': 'JavaScript', '.jsx': 'JavaScript/React',
  '.py': 'Python',     '.go': 'Go',
  '.rs': 'Rust',       '.java': 'Java',
  '.php': 'PHP',       '.rb': 'Ruby',
  '.vue': 'Vue',       '.svelte': 'Svelte',
  '.css': 'CSS',       '.scss': 'SCSS',
  '.sql': 'SQL',       '.prisma': 'Prisma',
};

// Framework detection by file presence
const FRAMEWORK_SIGNALS = [
  { file: 'next.config.js',        name: 'Next.js' },
  { file: 'next.config.ts',        name: 'Next.js' },
  { file: 'nuxt.config.ts',        name: 'Nuxt.js' },
  { file: 'vite.config.ts',        name: 'Vite' },
  { file: 'remix.config.js',       name: 'Remix' },
  { file: 'astro.config.mjs',      name: 'Astro' },
  { file: 'svelte.config.js',      name: 'SvelteKit' },
  { file: 'angular.json',          name: 'Angular' },
  { file: 'manage.py',             name: 'Django' },
  { file: 'requirements.txt',      name: 'Python' },
  { file: 'Cargo.toml',            name: 'Rust' },
  { file: 'go.mod',                name: 'Go' },
  { file: 'composer.json',         name: 'PHP/Laravel' },
  { file: 'artisan',               name: 'Laravel' },
];

const IGNORE_DIRS = [
  '**/node_modules/**', '**/.git/**', '**/dist/**',
  '**/build/**', '**/.next/**', '**/coverage/**',
  '**/.agent/**', '**/vendor/**', '**/__pycache__/**'
];

export async function scanProject(cwd = process.cwd()) {
  const result = {
    stack:      [],
    frameworks: [],
    languages:  {},
    structure:  [],
    fileCount:  0,
    hasTests:   false,
    hasPrisma:  false,
    hasDocker:  false,
    packageJson: null,
    gitIgnore:  null,
  };

  // Read package.json if exists
  const pkgPath = join(cwd, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      result.packageJson = JSON.parse(readFileSync(pkgPath, 'utf8'));
      result.stack.push(...detectFromPackageJson(result.packageJson));
    } catch {}
  }

  // Detect frameworks by file presence
  for (const signal of FRAMEWORK_SIGNALS) {
    if (existsSync(join(cwd, signal.file))) {
      result.frameworks.push(signal.name);
    }
  }

  // Scan all files
  const files = await fg('**/*', {
    cwd,
    ignore: IGNORE_DIRS,
    onlyFiles: true,
    dot: false,
  });

  result.fileCount = files.length;

  // Count languages
  for (const file of files) {
    const ext = extname(file);
    if (LANG_MAP[ext]) {
      result.languages[LANG_MAP[ext]] = (result.languages[LANG_MAP[ext]] || 0) + 1;
    }
    if (file.includes('.test.') || file.includes('.spec.') || file.includes('__tests__')) {
      result.hasTests = true;
    }
    if (file.endsWith('.prisma')) result.hasPrisma = true;
    if (file === 'Dockerfile' || file === 'docker-compose.yml') result.hasDocker = true;
  }

  // Build top-level structure
  const topLevel = await fg('*', {
    cwd,
    ignore: IGNORE_DIRS,
    onlyDirectories: true,
  });
  result.structure = topLevel;

  return result;
}

function detectFromPackageJson(pkg) {
  const stack = [];
  const allDeps = {
    ...pkg.dependencies || {},
    ...pkg.devDependencies || {}
  };

  const checks = [
    ['react',          'React'],
    ['vue',            'Vue'],
    ['svelte',         'Svelte'],
    ['express',        'Express'],
    ['fastify',        'Fastify'],
    ['prisma',         'Prisma'],
    ['mongoose',       'MongoDB/Mongoose'],
    ['typeorm',        'TypeORM'],
    ['drizzle-orm',    'Drizzle ORM'],
    ['tailwindcss',    'Tailwind CSS'],
    ['@mui/material',  'Material UI'],
    ['next-auth',      'NextAuth'],
    ['@clerk/nextjs',  'Clerk Auth'],
    ['zod',            'Zod'],
    ['trpc',           'tRPC'],
    ['graphql',        'GraphQL'],
    ['socket.io',      'Socket.io'],
    ['jest',           'Jest'],
    ['vitest',         'Vitest'],
    ['playwright',     'Playwright'],
  ];

  for (const [dep, name] of checks) {
    if (allDeps[dep]) stack.push(name);
  }

  return stack;
}

export function buildFileMap(scanResult, cwd) {
  const lines = [];

  lines.push('# Project File Map');
  lines.push(`> Generated by Cortex | ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // Frameworks & Stack
  if (scanResult.frameworks.length > 0) {
    lines.push('## Frameworks');
    for (const f of scanResult.frameworks) lines.push(`- ${f}`);
    lines.push('');
  }

  if (scanResult.stack.length > 0) {
    lines.push('## Stack & Libraries');
    for (const s of scanResult.stack) lines.push(`- ${s}`);
    lines.push('');
  }

  // Languages
  const langs = Object.entries(scanResult.languages)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);
  if (langs.length > 0) {
    lines.push('## Languages');
    for (const [lang, count] of langs) {
      lines.push(`- ${lang}: ${count} files`);
    }
    lines.push('');
  }

  // Directory structure
  if (scanResult.structure.length > 0) {
    lines.push('## Directory Structure');
    for (const dir of scanResult.structure) {
      lines.push(`- \`${dir}/\``);
    }
    lines.push('');
  }

  // Features detected
  const features = [];
  if (scanResult.hasTests)  features.push('Tests');
  if (scanResult.hasPrisma) features.push('Prisma ORM');
  if (scanResult.hasDocker) features.push('Docker');
  if (features.length > 0) {
    lines.push('## Detected Features');
    for (const f of features) lines.push(`- ${f}`);
    lines.push('');
  }

  lines.push(`## Stats`);
  lines.push(`- Total files: ${scanResult.fileCount}`);

  return lines.join('\n');
}
